description: "retryable reads handshake failures"

schemaVersion: "1.3"

runOnRequirements:
  - minServerVersion: "4.2"
    topologies: [replicaset, sharded, load-balanced]
    auth: true

createEntities:
  - client:
      id: &client0 client0
      useMultipleMongoses: false
      observeEvents: [commandStartedEvent, connectionCheckOutStartedEvent]
  - database:
      id: &database0 database0
      client: *client0
      databaseName: &databaseName retryable-handshake-tests
  - collection:
      id: &collection0 collection0
      database: *database0
      collectionName: &collectionName coll

initialData:
  - collectionName: *collectionName
    databaseName: *databaseName
    documents:
      - { _id: 1, x: 11 }
      - { _id: 2, x: 22 }
      - { _id: 3, x: 33 }

tests:
  - description: "find succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              # use saslContinue here to avoid SDAM errors
              # this failPoint itself will create a usable connection in the connection pool
              # so we run a ping (that also fails) in order to discard the connection
              # before testing our read operation "find"
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: find
        object: *collection0
        arguments:
          filter: { _id: 2 }
        expectResult: [{ _id: 2, x: 22 }]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                find: *collectionName
                filter: { _id: 2 }
              commandName: find
              databaseName: *databaseName

  - description: "find succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: find
        object: *collection0
        arguments:
          filter: { _id: 2 }
        expectResult: [{ _id: 2, x: 22 }]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                find: *collectionName
                filter: { _id: 2 }
              commandName: find
              databaseName: *databaseName

  - description: "aggregate succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: aggregate
        object: *collection0
        arguments:
          pipeline: [{ $match: { _id: { $gt: 1 } } }]
          batchSize: 2
        expectResult:
          - { _id: 2, x: 22 }
          - { _id: 3, x: 33 }

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                aggregate: *collectionName
                pipeline: [{ $match: { _id: { $gt: 1 } } }]
                cursor: { batchSize: 2 }
              commandName: aggregate
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                getMore: { $$type: [int, long] }
                collection: *collectionName
                batchSize: 2
              commandName: getMore
              databaseName: *databaseName

  - description: "aggregate succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: aggregate
        object: *collection0
        arguments:
          pipeline: [{ $match: { _id: { $gt: 1 } } }]
          batchSize: 2
        expectResult:
          - { _id: 2, x: 22 }
          - { _id: 3, x: 33 }

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                aggregate: *collectionName
                pipeline: [{ $match: { _id: { $gt: 1 } } }]
                cursor: { batchSize: 2 }
              commandName: aggregate
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                getMore: { $$type: [int, long] }
                collection: *collectionName
                batchSize: 2
              commandName: getMore
              databaseName: *databaseName

  - description: "distinct succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: distinct
        object: *collection0
        arguments:
          fieldName: x
          filter: {}
        expectResult: [11, 22, 33]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                distinct: *collectionName
                key: x
                query: {}
              commandName: distinct
              databaseName: *databaseName

  - description: "distinct succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: distinct
        object: *collection0
        arguments:
          fieldName: x
          filter: {}
        expectResult: [11, 22, 33]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                distinct: *collectionName
                key: x
                query: {}
              commandName: distinct
              databaseName: *databaseName

  - description: "estimatedDocumentCount succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: estimatedDocumentCount
        object: *collection0
        expectResult: 3

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                count: *collectionName
              commandName: count
              databaseName: *databaseName

  - description: "estimatedDocumentCount succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: estimatedDocumentCount
        object: *collection0
        expectResult: 3

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                count: *collectionName
              commandName: count
              databaseName: *databaseName

  - description: "countDocuments succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: countDocuments
        object: *collection0
        arguments:
          filter: {}
        expectResult: 3

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                aggregate: *collectionName
                pipeline:
                  - $match: {}
                  - $group: { _id: 1, n: { $sum: 1 } }
              commandName: aggregate
              databaseName: *databaseName

  - description: "countDocuments succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: countDocuments
        object: *collection0
        arguments:
          filter: {}
        expectResult: 3

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                aggregate: *collectionName
                pipeline:
                  - $match: {}
                  - $group: { _id: 1, n: { $sum: 1 } }
              commandName: aggregate
              databaseName: *databaseName

  - description: "listDatabases succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listDatabases
        object: *client0
        ignoreResultAndError: true # Assume success.

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} } # Network error.
          - { connectionCheckOutStartedEvent: {} } # Successful retry.
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listDatabases: 1
                $db: admin
              commandName: listDatabases

  - description: "listDatabases succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listDatabases
        object: *client0
        ignoreResultAndError: true # Assume success.

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} } # Network error.
          - { connectionCheckOutStartedEvent: {} } # Successful retry.
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listDatabases: 1
                $db: admin
              commandName: listDatabases

  - description: "listCollections succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listCollections
        object: *database0
        expectResult: [{ name: *collectionName }]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listCollections: 1
                $db: *databaseName
              commandName: listCollections

  - description: "listCollections succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listCollections
        object: *database0
        expectResult: [{ name: *collectionName }]

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listCollections: 1
                $db: *databaseName
              commandName: listCollections

  - description: "listIndexes succeeds after retryable handshake network error"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              closeConnection: true

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listIndexes
        object: *collection0
        ignoreResultAndError: true # Assume success.

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} } # Network error.
          - { connectionCheckOutStartedEvent: {} } # Successful retry.
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listIndexes: *collectionName
              commandName: listIndexes

  - description: "listIndexes succeeds after retryable handshake network error (ShutdownInProgress)"
    operations:
      - name: failPoint # fail the next connection establishment
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [saslContinue, ping]
              errorCode: 91 # ShutdownInProgress

      - name: runCommand
        object: *database0
        arguments:
          commandName: ping
          command: { ping: 1 }
        expectError:
          isError: true

      - name: listIndexes
        object: *collection0
        ignoreResultAndError: true # Assume success.

    expectEvents:
      - client: *client0
        eventType: cmap
        events:
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} }
          - { connectionCheckOutStartedEvent: {} } # Network error.
          - { connectionCheckOutStartedEvent: {} } # Successful retry.
      - client: *client0
        events:
          - commandStartedEvent:
              command:
                ping: 1
              databaseName: *databaseName
          - commandStartedEvent:
              command:
                listIndexes: *collectionName
              commandName: listIndexes
