database_name: &database_name "retryable-reads-tests"
collection_name: &collection_name "coll"

data:
    - { _id: 1, x: 11 }
    - { _id: 2, x: 22 }

minServerVersion: '4.1.6' # 4.2

tests:
    -
        description: "CountDocuments succeeds after InterruptedAtShutdown"
        clientOptions:
            retryReads: true
        failPoint: &failCommand_failPoint
            configureFailPoint: failCommand
            mode: { times: 1 }
            data: { failCommands: [aggregate], errorCode: 11600 }
        operation: &retryable_operation
            name: countDocuments
            object: collection
            arguments:
                filter: { }
            result: 2
        expectations:
             - &retryable_command_started_event
                command_started_event:
                    command:
                        aggregate: *collection_name
                        pipeline: [{'$match': {}}, {'$group': {'_id': null, 'n': {'$sum': 1}}}]
                    database_name: *database_name
             - *retryable_command_started_event
    -
        description: "CountDocuments succeeds after InterruptedDueToStepDown"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 11602 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after NotMaster"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 10107 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after NotMasterNoSlaveOk"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 13435 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after NotMasterOrSecondary"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 13436 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after PrimarySteppedDown"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 189 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after ShutdownInProgress"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 91 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after HostNotFound"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 7 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after HostUnreachable"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 6 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after NetworkTimeout"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 89 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "CountDocuments succeeds after SocketException"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [aggregate], errorCode: 9001 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event 
