database_name: &database_name "retryable-reads-tests"
collection_name: &collection_name "coll"

data:
    - { _id: 1, x: 11 }
    - { _id: 2, x: 22 }

minServerVersion: '4.1.6' # 4.2

tests:
    -
        description: "Count succeeds after InterruptedAtShutdown"
        clientOptions:
            retryReads: true
        failPoint: &failCommand_failPoint
            configureFailPoint: failCommand
            mode: { times: 1 }
            data: { failCommands: [count], errorCode: 11600 }
        operation: &retryable_operation
            name: count
            object: collection
            arguments: { filter: { } }
            result: 2
        expectations:
            - &retryable_command_started_event
                command_started_event:
                    command:
                        count: *collection_name
                    database_name: *database_name
            - *retryable_command_started_event
    -
        description: "Count succeeds after InterruptedDueToStepDown"
        clientOptions:
            retryReads: true
        failPoint: 
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 11602 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after NotMaster"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 10107 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after NotMasterNoSlaveOk"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 13435 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after NotMasterOrSecondary"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 13436 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after PrimarySteppedDown"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 189 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after ShutdownInProgress"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 91 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after HostNotFound"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 7 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after HostUnreachable"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 6 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after NetworkTimeout"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 89 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Count succeeds after SocketException"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 9001 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event
    -
        description: "Count fails after two NotMaster errors"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            mode: { times: 2 }
            data: { failCommands: [count], errorCode: 10107 }
        operation:
            <<: *retryable_operation
            result: 
                error: true
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event               
    -
        description: "Count fails after NotMaster when retryReads is false"
        clientOptions:
            retryReads: false
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [count], errorCode: 10107 }
        operation:
            <<: *retryable_operation
            result: 
                error: true
        expectations:
             - *retryable_command_started_event
  
