{
  "version": 1,
  "style": "integration",
  "description": "checking in a connection after checkout fails closes connection",
  "runOn": [
    {
      "minServerVersion": "4.9.0"
    }
  ],
  "poolOptions": {
    "appName": "poolCheckOutErrorCheckInTest"
  },
  "operations": [
    {
      "name": "ready"
    },
    {
      "name": "checkOut",
      "label": "conn"
    },
    {
      "name": "failPoint",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 10
        },
        "data": {
          "failCommands": [
            "isMaster",
            "hello"
          ],
          "closeConnection": true,
          "appName": "poolCheckOutErrorCheckInTest"
        }
      }
    },
    {
      "name": "start",
      "target": "thread1"
    },
    {
      "name": "checkOut",
      "thread": "thread1"
    },
    {
      "name": "waitForEvent",
      "event": "ConnectionCheckOutFailed",
      "count": 1
    },
    {
      "name": "checkIn",
      "connection": "conn"
    }
  ],
  "events": [
    {
      "type": "ConnectionCheckOutStarted"
    },
    {
      "type": "ConnectionCreated"
    },
    {
      "type": "ConnectionReady"
    },
    {
      "type": "ConnectionCheckedOut"
    },
    {
      "type": "ConnectionCheckOutStarted"
    },
    {
      "type": "ConnectionCreated"
    },
    {
      "type": "ConnectionPoolCleared"
    },
    {
      "type": "ConnectionClosed",
      "reason": "error",
      "connectionId": 2
    },
    {
      "type": "ConnectionCheckOutFailed",
      "reason": "connectionError"
    },
    {
      "type": "ConnectionCheckedIn"
    },
    {
      "type": "ConnectionClosed",
      "connectionId": 1,
      "reason": "stale"
    }
  ],
  "ignore": [
    "ConnectionPoolCreated",
    "ConnectionPoolReady"
  ]
}
