{
  "data": [
    {
      "_id": 1,
      "x": 11
    }
  ],
  "minServerVersion": "3.6",
  "tests": [
    {
      "description": "DeleteOne fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "deleteOne",
        "arguments": {
          "filter": {
            "_id": 1
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": []
        }
      }
    },
    {
      "description": "FindOneAndDelete fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "FindOneAndDelete",
        "arguments": {
          "filter": {
            "_id": 1
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": []
        }
      }
    },
    {
      "description": "FindOneAndReplace fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "FindOneAndReplace",
        "arguments": {
          "filter": {
            "_id": 1
          },
          "replacement": {
            "_id": 1,
            "x": 111
          },
          "returnDocument": "Before"
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 111
            }
          ]
        }
      }
    },
    {
      "description": "FindOneAndUpdate fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "FindOneAndUpdate",
        "arguments": {
          "filter": {
            "_id": 1
          },
          "update": {
            "$inc": {
              "x": 1
            }
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 12
            }
          ]
        }
      }
    },
    {
      "description": "InsertOne fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "insertOne",
        "arguments": {
          "document": {
            "_id": 2,
            "x": 22
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      }
    },
    {
      "description": "ReplaceOne fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "replaceOne",
        "arguments": {
          "filter": {
            "_id": 1
          },
          "replacement": {
            "_id": 1,
            "x": 111
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 111
            }
          ]
        }
      }
    },
    {
      "description": "UpdateOne fails after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "updateOne",
        "arguments": {
          "filter": {
            "_id": 1
          },
          "update": {
            "$inc": {
              "x": 1
            }
          }
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 12
            }
          ]
        }
      }
    },
    {
      "description": "UpdateOne fails with upsert after multiple network errors",
      "failPoint": {
        "times": 2
      },
      "operation": {
        "name": "updateOne",
        "arguments": {
          "filter": {
            "_id": 2,
            "x": 22
          },
          "update": {
            "$inc": {
              "x": 1
            }
          },
          "upsert": true
        }
      },
      "outcome": {
        "error": true,
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 23
            }
          ]
        }
      }
    }
  ]
}
